name: 🐞 Bug report
description: Report a problem or unexpected behavior in Universal Schema Studio
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!  
        Please fill out the information below so we can reproduce and fix it quickly.

  - type: input
    id: version
    attributes:
      label: App version / Build
      description: Which version or commit are you using?
      placeholder: e.g. v1.2.3 or commit abc123
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? Include screenshots or logs if possible.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe the issue...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: It should display the parsed schema correctly.
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser and OS
      description: What browser and operating system are you using?
      placeholder: e.g. Chrome 141 on Windows 10
    validations:
      required: true

  - type: dropdown
    id: theme
    attributes:
      label: Theme Mode
      description: Which theme was active when the issue occurred?
      options:
        - Light
        - Dark
        - Both
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: Logs, console errors, screenshots, etc.