// js/exporter/exportMarkdown.js

export function exportMarkdown(doc) {
  const lines = [];

  const { meta, overview, endpoints, schemas, enums } = doc;

// =====================================================
// 📚 TABLE OF CONTENTS (MARKDOWN)
// =====================================================
lines.push("## Table of Contents");
lines.push("");

doc.toc.sections.forEach((sec, i) => {
  const anchor = sec.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  lines.push(`${i + 1}. [${sec.title}](#${anchor})`);

  if (sec.children && sec.children.length) {
    sec.children.forEach((child) => {
      const childAnchor = child.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      lines.push(`   - [${child.title}](#${childAnchor})`);
    });
  }
});
lines.push("");
lines.push("---");
lines.push("");

  // ==============================
  // HEADER
  // ==============================
  lines.push(`# ${meta.title}`);
  lines.push(`Version: \`${meta.version}\``);
  lines.push(`Generated: \`${meta.generatedAt}\``);
  lines.push("");
  lines.push("---");
  lines.push("");

  if (meta.description) {
    lines.push(`> ${meta.description}`);
    lines.push("");
  }

  // ==============================
  // OVERVIEW
  // ==============================
  lines.push("## 1. Overview");
  lines.push("");
  lines.push(`- Total Schemas: **${overview.totalSchemas}**`);
  lines.push(`- Total Endpoints: **${overview.totalEndpoints}**`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ==============================
  // ENDPOINTS
  // ==============================
  lines.push("## 2. Endpoints");
  lines.push("");

  if (!endpoints.length) {
    lines.push("_No endpoints defined._");
    lines.push("");
  }

  endpoints.forEach((ep, i) => {
    lines.push(`### 2.${i + 1} \`${ep.method.toUpperCase()} ${ep.path}\``);
    if (ep.summary) lines.push(`**Summary:** ${ep.summary}`);
    if (ep.description) lines.push(ep.description);
    lines.push("");

    // Request example
    if (ep.requestBodyExample) {
      lines.push("**Example Request:**");
      lines.push("```json");
      lines.push(JSON.stringify(ep.requestBodyExample, null, 2));
      lines.push("```");
      lines.push("");
    }

    // Responses
    if (ep.responses.length) {
      lines.push("**Responses:**");
      lines.push("");
      ep.responses.forEach((r) => {
        lines.push(`#### ${r.status}`);
        if (r.description) lines.push(r.description);
        if (r.example) {
          lines.push("```json");
          lines.push(JSON.stringify(r.example, null, 2));
          lines.push("```");
        }
        lines.push("");
      });
    }

    lines.push("");
  });

  lines.push("---");
  lines.push("");

  // ==============================
  // SCHEMAS
  // ==============================
  lines.push("## 3. Schemas");
  lines.push("");

  schemas.forEach((s, i) => {
    lines.push(`### 3.${i + 1} \`${s.name}\``);
    lines.push(`**Type:** ${s.type}`);
    if (s.description) lines.push(s.description);
    lines.push("");

    if (s.properties.length) {
      lines.push("**Properties:**");
      lines.push("");
      lines.push("| Name | Type | Format | Required | Description |");
      lines.push("|------|------|--------|----------|-------------|");
      s.properties.forEach((p) => {
        lines.push(
          `| \`${p.name}\` | \`${p.type || ""}\` | \`${p.format || ""}\` | ${
            p.required ? "yes" : "no"
          } | ${p.description || ""} |`
        );
      });
      lines.push("");
    }

    lines.push("");
  });

  lines.push("---");
  lines.push("");

  // ==============================
  // ENUMS
  // ==============================
  lines.push("## 4. Enums");
  lines.push("");

  if (!enums.length) {
    lines.push("_No enums defined._");
  } else {
    enums.forEach((en, i) => {
      lines.push(`### 4.${i + 1} \`${en.name}\``);
      if (en.description) lines.push(en.description);
      lines.push("");
      lines.push("Values:");
      en.values.forEach((v) => lines.push(`- \`${v.value}\``));
      lines.push("");
    });
  }

  // ==============================
  // FOOTER
  // ==============================
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `Documentation generated by **Universal Schema Studio**  
https://schema.mumblebaj.xyz`
  );

  return lines.join("\n");
}
